export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const ASYNC_INCREMENT_STARTED = 'ASYNC_INCREMENT_STARTED';
export const ASYNC_INCREMENT_SUCCESS = 'ASYNC_INCREMENT_SUCCESS';
export const ASYNC_INCREMENT_FAILURE = 'ASYNC_INCREMENT_FAILURE';
